### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by yellow-starburst** [vletoux/SpoolerScanner#1]
https://github.com/vletoux/SpoolerScanner/blob/64d20951d28ee0e64269ddf43031298e15089f73/SpoolerScan.ps1#L723
Unexpected token '192.168.0.20' in expression or statement.
At line:1 char:45
+ $rprn.CheckIfTheSpoolerIsActive "192.168.0.20" <<<<
    + CategoryInfo          : ParserError: (192.168.0.20:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by vletoux** [comment]
The parenthesis are missing...
